### ISSUE TITLE
Prototyping for EME 150A

### ISSUE THREAD

**Issue by moorepants** [moorepants/eng-edu#1]
The students in EME 150A design a front mounted bicycle rack for a Unitrans bus as a design project. See the description of the project here:

http://moorepants.github.io/eme150a-website/pages/project-two-unitrans-bicycle-rack-design.html

Example designs can be found here:

http://www.moorepants.info/blog/eme150a-fall-2015.html

We use a number of the discussion sections for EME 150A to do various design activities. I want to introduce a "lightweight prototyping" activity for at least one of the sessions. The students should have at least 1 or 2 sketches of different bicycle rack designs per student in the team (team of 4 or 5). I'd like the students to construct scale models of the different bicycle racks during a 50 minute session.

Objectives:
- Students will be able to utilize quick, simple, scale models to help make
  mechanical design decisions.
- Students will be able to judge structural integrity of mechanical structures
  with scale models.

Needs:
- Inexpensive materials for prototyping
- Maybe some scale bicycle toys, one per team so that they can build the racks
  around them.
- Quick joinery methods (sets up fast if glue or is fixed instantly)

Some ideas:
- Bend stiff wire (like coat hanger stiffness) with pliers into shapes and join
  them with small soft wire or maybe even 

Tasks:
- [x] Find some cheap 1:12 scale toy bicycles.
- [x] Test out making the racks with various materials.

**Comment by moorepants** [comment]
- [ ] sub task 1
- [ ] sub task 2

**Comment by viviantran27** [comment]
Here are some 1:10 scale toy bicycles options on ebay. They're both ~$18 (including shipping).

http://www.ebay.com/itm/like/142016212510?item=142016212510&lgeo=1&vectorid=229466&rmvSB=true

http://www.ebay.com/itm/like/351746660695?item=351746660695&lgeo=1&vectorid=229466&rmvSB=true

Another option would be to 3D print one (e.g. http://www.thingiverse.com/thing:763225).

**Comment by viviantran27** [comment]
It took me ~3 hrs to prototype the roller bearing rack (probably the simplest one in my opinion) on my own, so students might be able to finish in a couple of discussions (assuming they have the tools to work on multiple parts simultaneously). I'll also continue to try finding a better material-adhesive combo to cut down the time. I used: 
pliers, 
a wire cutter, 
electrical tape to model the joint of the bar securing the tire and to connect two broken pieces of wire (hot glue didn't work but I'll try soldering when I have access to a soldering iron), 
box cutter (to cut cardboard strips)
a ruler, 
sharpie, 
~2 hot glue sticks and a hot glue gun.
Materials were ~5 popsicle sticks, cardboard, and 2 wire hangers, 

Other ideas would be to use hanger wire  + solder, styrofoam board + hot glue, and popsicle sticks + hot glue (thin and jumbo). 
![img_2541](https://cloud.githubusercontent.com/assets/6379429/16535135/dea168ce-3f99-11e6-80eb-78ad4f77d4be.JPG)
![img_2539](https://cloud.githubusercontent.com/assets/6379429/16535138/e6d5163a-3f99-11e6-8692-58a26aced0ab.JPG)

**Comment by viviantran27** [comment]
These were some of the wood options from Michael's. It's nice since they come in a nice variety of shapes and sizes, but most parts with curvature are nearly impossible to model. Also, splitting from cutting in the direction of the grain means some dimensions of the pre-cut pieces won't be adjustable.
![img_2554](https://cloud.githubusercontent.com/assets/6379429/16906388/d557c61c-4c6b-11e6-8a2f-7505814243a6.JPG)
![img_2553](https://cloud.githubusercontent.com/assets/6379429/16906389/d5592408-4c6b-11e6-976c-23ac0522f0bc.JPG)

**Comment by viviantran27** [comment]
Wooden prototype took ~2.5 hours to complete. Metal prototype took ~2 hours to finish most of one structure.
![img_2607](https://cloud.githubusercontent.com/assets/6379429/17266088/62342bf2-55a9-11e6-8bd9-2f68b05f37c4.JPG)
![img_2605](https://cloud.githubusercontent.com/assets/6379429/17266089/623cb24a-55a9-11e6-9647-7fe27cd432a4.JPG)

**Comment by moorepants** [comment]
Cool, so the wooden will be faster.

**Comment by viviantran27** [comment]
The thickness of the aluminum can is ~.008" (Al foil is ~.00063"). I looked on McMaster Carr for steel sheet options of about the same thickness or thinner that wasn't 

![1](https://cloud.githubusercontent.com/assets/6379429/17343607/73e5b868-58b3-11e6-901a-4bee6b15587e.PNG)
^Multipurpose 304 Stainless Steel (Being annealed makes it more malleable and probably easier to work with)
![2](https://cloud.githubusercontent.com/assets/6379429/17343608/751e6af4-58b3-11e6-8078-a8f3b89aa074.PNG)
^Just another option 
![3](https://cloud.githubusercontent.com/assets/6379429/17343610/76c160d2-58b3-11e6-8ae8-41183bd7b3e4.PNG)
^Cheapest option

I was wondering what your opinions were on the different types of steel for prototyping purposes.

**Comment by viviantran27** [comment]
Zinc boils at ~907 C, while typical soldering irons gets up to about ~370 C. It seems fumes won't be an issue, but just in case, there're non-galvanized options on McMaster Carr.
![wire](https://cloud.githubusercontent.com/assets/6379429/17345311/40851cf0-58ba-11e6-8887-fca04bc282cb.PNG)

**Comment by moorepants** [comment]
It'd be more economical if we didn't buy things from McMaster. McMaster has premium on its stuff because you can buy in low quantities and have it shipped immediately. For a long solution , we should see if a local metal dealer, e.g. Blue Collar Supply, would have some material. It's possible that a hobby shop would have material too.

**Comment by viviantran27** [comment]
Blue Collar Supply's thinnest steel sheet is 20 gauge. 
I'm looking into metal duct hangar strap rolls 
e.g. http://thesheetmetalkid.com/accessories/26-gauge-galvanized-steel-sheet-metal-duct-hanger-strap/ .

**Comment by viviantran27** [comment]
I'd suggest this 1:10 model bike for prototyping purposes. It's the latter of the 2 links I posted, the only difference is the color (this one is blue while the other is black) and a few cents. It's about 7.7" long which is about .5" longer than my prototypes, but it's in the same ballpark. 

http://www.ebay.com/itm/DIECAST-MODEL-COLLECTIONS-1-10-RACING-BIKE-BICYCLE-REPLICA-TOY-/351746660695?_trksid=p2141725.m3641.l6368&autorefresh=true

**Comment by viviantran27** [comment]
I put in an order for some materials at Michael's (store pick up) that needs your approval.

**Comment by viviantran27** [comment]
Who do I send the office supply list to again?
