### ISSUE TITLE
Broken shelf under TV in design studio

### ISSUE THREAD

**Issue by moorepants** [moorepants/eng-edu#11]
The glass shelving we purchased to hold the computer and keyboard under the tv broke. Maybe we can remove the glass and add some sturdier wooden replacements that are bigger and won't break. Or we can find a podium for the wireless keyboard/mouse use.

**Comment by viviantran27** [comment]
Looking into making a wooden replacement with ESSC's ShopBot.

**Comment by viviantran27** [comment]
![image](https://cloud.githubusercontent.com/assets/6379429/17826970/ef5af664-662a-11e6-8a9e-57706784958f.png)
Glass shelf and original screws are in the podium/ cart's cabinet.

**Comment by moorepants** [comment]
Very nice work!
